- name: write env vars
  with_items:
    - 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"'
    - 'PAGER="less -r"'
    - "export PAGER"
    - "export PATH"
  lineinfile:
    path: /etc/bashrc
    line: "{{ item }}"

- name: hostname
  hostname:
    name: "{{ fqdn }}"

- name: hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644

- name: Configure sshd
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - key: "PermitRootLogin"
      value: "no"
    - key: "PasswordAuthentication"
      value: "yes"
  notify:
    - restart ssh
